server:
  port: 7777

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:33066/ss_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    # 文件上传
    multipart:
      # 单个上传文件的最大允许大小
      max-file-size: 20MB
      # HTTP请求中包含的所有文件的总大小的最大允许值
      max-request-size: 20MB

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除的字段
      logic-delete-field: delFlag
      # 代表已删除的值
      logic-delete-value: 1
      # 代表未删除的值
      logic-not-delete-value: 0
      # 主键自增策略，以mysql数据库为准
      id-type: auto

oss:
  accessKey: A7PMrF4gXp-ioKQ_lYHhNTDsggupUvT1fie3YV7C
  secretKey: hw4xtb98jBYKKULpYSJEIqD50jiEzNnz6N1bUcEX
  bucket: sinsra-blog
  dns: http://sd2ga2g2m.hn-bkt.clouddn.com/